config/routes.rb
Rails.application.routes.draw do
  resources :missions
  resources :scientists
  resources :planets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :planet
  belongs_to :scientist

  validates :name, :scientist, :planet, presence: true
  validates :name,  uniqueness: true

end

app/models/planet.rb
class Planet < ApplicationRecord

    has_many :missions
    has_many :scientists, through: :missions
    
end

app/models/scientist.rb
class Scientist < ApplicationRecord

    has_many :missions, :dependent => :destroy
    has_many :planets, through: :missions

    validates :name, :field_of_study, presence: true
    validates :name, uniqueness: true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

    def index
        @missions = Mission.all
    end

    def show
        @mission = Mission.find(params[:id])
    end

    def new
    @mission = Mission.new
    @planets = Planet.all
    @scientists = Scientist.all 
    end

    def create
    @mission = Mission.create(mission_params)
    if @mission.valid?
    redirect_to scientist_path(@mission.scientist.id)
    else  
        flash[:my_errors] = @mission.errors.full_messages
        redirect_to new_mission_path
    end
    end

    private

    def mission_params
        params.require(:mission).permit(:planet_id, :scientist_id, :name)
    end 
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

    def index
    @planets = Planet.all  
    end

    def show
    @planet = Planet.find(params[:id])
    end
    
end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController

    def index
        @scientists = Scientist.all 
    end

    def show
        @scientist = Scientist.find(params[:id])
    end

    def new
        @scientist = Scientist.new
    end

    def create
        @scientist = Scientist.create(scientist_params)
        if @scientist.valid?
        redirect_to scientist_path(@scientist.id)
        else  
            flash[:my_errors] = @scientist.errors.full_messages
            redirect_to new_scientist_path
        end
    end

    def edit
        @scientist = Scientist.find(params[:id])
    end

    def update
        @scientist = Scientist.find(params[:id])
        if @scientist.update(scientist_params)
        redirect_to scientist_path(@scientist.id)
        else   
            flash[:my_errors] = @scientist.errors.full_messages
            redirect_to edit_scientist_path
        end
    end

    def destroy
        @scientist = Scientist.find(params[:id])
        @scientist.destroy 
        redirect_to scientists_path
    end

    private

    def scientist_params
    params.require(:scientist).permit(:name, :field_of_study)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/scientists_helper.rb
module ScientistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlanetaryMissions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/missions/index.html.erb
<h1>List of Missions</h1>

<% @missions.each do |mission| %>
<p><%= link_to mission.name, mission_path(mission) %>
<% end %>

<p><%= link_to "Create a New Mission", new_mission_path %></p>

app/views/missions/new.html.erb
<h1>Create a New Mission:</h1>

<% if flash[:my_errors] %>
<% flash[:my_errors].each do |error| %>
<p><%= error %><p>
<% end %>
<% end %>

<%= form_for @mission do |f| %>
<%= f.label :name, value = "Mission Name" %>
<%= f.text_field :name %>

<%= f.label :planet_id %>
<%= f.collection_select :planet_id, @planets, :id, :name %>

<%= f.label :scientist_id %>
<%= f.collection_select :scientist_id, @scientists, :id, :name %>

<%= f.submit %>

<% end %>

app/views/missions/show.html.erb
<h1>Mission Name: <%= @mission.name %></h1>

<p>Scientist: <%= link_to @mission.scientist.name, scientist_path(@mission.scientist.id) %></p>

<p>Planet Explored: <%= link_to @mission.planet.name, planet_path(@mission.planet.id) %></p>

app/views/planets/index.html.erb
<h1>Planets Explored:</h1>

<% @planets.each do |planet| %>
<p><%= link_to planet.name, planet_path(planet) %>
<% end %>

app/views/planets/show.html.erb
<h2>Planet Name: <%= @planet.name %></h2>

<p>Distance from Earth: <%= @planet.distance_from_earth %></p>
<p>Nearest Star: <%= @planet.nearest_star %></p>

<h4>Missions to <%= @planet.name %>:</h4>

<% @planet.missions.each do |mission| %>
<p><%= link_to mission.name, mission_path(mission.id) %><p>
<% end %>

app/views/scientists/_form.html.erb
<% if flash[:my_errors] %>
<% flash[:my_errors].each do |error| %>
<p><%= error %></p>
<% end %>
<% end %>

<%= form_for @scientist do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :field_of_study %>
<%= f.text_field :field_of_study %>

<%= f.submit %>
<% end %>

app/views/scientists/edit.html.erb
<h1>Edit this Scientist</h1>

<%= render 'form' %>

app/views/scientists/index.html.erb
<h1>Presenting ALL THE SCIENTISTS!!</h1>

<% @scientists.each do |scientist| %>
<p><%= link_to scientist.name, scientist_path(scientist) %>
<% end %>



<p><%= link_to "Create a New Scientist", new_scientist_path %></p>

app/views/scientists/new.html.erb
<h1>Create a New Scientist</h1>

<%= render 'form'%>

app/views/scientists/show.html.erb
<h1><%= @scientist.name %></h1>

<p>Field of Study: <%= @scientist.field_of_study %></p>

<h4>Missions:</h4>
<% @scientist.missions.each do |mission| %>
<p><%= link_to mission.name, mission_path(mission) %><p>
<% end %>

<h4>Planets Explored:</h4>
<% @scientist.planets.each do |planet| %>
<p><%= link_to planet.name, planet_path(planet) %></p>
<% end %>

<p><%= link_to "Edit this Scientist", edit_scientist_path %></p>

<p><%= button_to "Delete this Scientist", scientist_path(@scientist), method: :delete %>